### ISSUE TITLE
로그인및 회원가입 퍼블리싱 및 기능 작업

### ISSUE THREAD

**Issue by TaeYoungPar** [SFACLOG/sfaclog#25]
퍼블리싱 및 기능 작업

### Todo

- [ ] 로그인, 회원가입, 비밀번호 찾기 퍼블리싱
- [ ] 로그인, 회원가입 인증 및 기능 작업
- [ ] 비밀번호 찾기 기능 작업
- [ ] 카카오auth 작업

### 작업 기간

내용을 작성해주세요(작성 예시: 2023.12.26 ~ 2023.12.26)

--문제점
비밀번호 찾기시 권한이 없어 변경이 불가(멘토링 해야함)
