### ISSUE TITLE
프로젝트 페이지 퍼블리싱

### ISSUE THREAD

**Issue by TaeYoungPar** [SFACLOG/sfaclog#27]
### Todo

- [ ] 사이드 프로젝트 메인
- [ ] 스펙폴리오 프로젝트 상세
- [ ] 스팩로그 프로젝트 모집 글쓰기
- [ ] 스팩로그 프로젝트 상세
- [ ] 스팩로그 프로젝트 관리

### 작업 기간

내용을 작성해주세요(작성 예시: 2023.12.26 ~ 2023.12.26)
2024.02.06~
---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요

### 참고 자료(optional)

> 참고자료가 있다면 첨부해주세요.
