### ISSUE TITLE
최신로그 페이지 퍼블리싱

### ISSUE THREAD

**Issue by seonnn** [SFACLOG/sfaclog#31]
### Todo

- [ ] 최신로그 페이지 퍼블리싱
  - [ ] 로그 태그 UI 작업
  - [ ] 페이지 전체 레이아웃 및 컴포넌트 배치

### 작업 기간

2024.02.07 ~
