### ISSUE TITLE
로그 작성 페이지 퍼블리싱

### ISSUE THREAD

**Issue by seonnn** [SFACLOG/sfaclog#32]
### Todo

- [ ] 로그 작성 페이지 퍼블리싱
  - [ ] WYSIWYG 라이브러리 결정 및 설치
  - [ ] 로그 작성 페이지 레이아웃 및 컴포넌트 배치

### 작업 기간

2024.02.07 ~
